project_id = "hfjtzmnphyizntcjzgar"

[functions.send-birthday-overlay-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-ios-push]
verify_jwt = false

[functions.arcana-ai]
verify_jwt = true

[functions.livekit-token]
verify_jwt = false
